# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fcb229644d8994303075e0b0a702b53f1e601823c3422aab623638e9c789153ae7fcaa6d5ec5571f686f196428a0c6e2571212300731963f1a7d8e9ea55746d

test:
  secret_key_base: 364c24fb842530fa9a69e3dbd47e8a20685bc53ead0c56dca2d373cbff36608479b8a411642839f5b4e984659066a7b11edab3f70f8642f1b12463d92d4490ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
